### ISSUE TITLE
Separate Organizers (admins) from Participants

### ISSUE THREAD

**Issue by Muirrum** [wpi-acm/Hack-WPI-Python#10]
Administrators should not be included in the participant count

**Comment by ngolp** [comment]
I addressed this issue in the branch "separate-users-admins" (https://github.com/wpi-acm/Hack-WPI-Python/tree/separate-users-admins).

I didn't know if I was supposed also to change the /mail route as shown below. Feel free to change it back!

![image](https://github.com/user-attachments/assets/15d2c991-2a6e-4956-9dc2-7e90cd3aecef)

**Comment by Muirrum** [comment]
Please do!
